namespace Umbraco.AI.Diagnostics.Models;

/// <summary>
/// Represents the complete analysis report generated by the AI diagnostics system.
/// </summary>
public class AnalysisReport
{
    /// <summary>
    /// Gets or sets the timestamp when the analysis was performed.
    /// </summary>
    public DateTime AnalysisTimestamp { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Gets or sets the total number of log entries analyzed.
    /// </summary>
    public int TotalLogsAnalyzed { get; set; }

    /// <summary>
    /// Gets or sets the number of unique log entries after deduplication.
    /// </summary>
    public int UniqueLogsCount { get; set; }

    /// <summary>
    /// Gets or sets the log levels that were analyzed.
    /// </summary>
    public List<string> AnalyzedLogLevels { get; set; } = new();

    /// <summary>
    /// Gets or sets the time range filter applied to the logs.
    /// </summary>
    public string TimeRange { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the list of individual log analysis items.
    /// </summary>
    public List<LogAnalysisItem> LogAnalysisItems { get; set; } = new();

    /// <summary>
    /// Gets or sets the AI-generated overall summary.
    /// </summary>
    public string? AISummary { get; set; }

    /// <summary>
    /// Gets or sets whether AI analysis was enabled for this report.
    /// </summary>
    public bool AIEnabled { get; set; }
}

/// <summary>
/// Represents analysis details for a specific log entry or group of similar logs.
/// </summary>
public class LogAnalysisItem
{
    /// <summary>
    /// Gets or sets the original log entry.
    /// </summary>
    public LogEntry LogEntry { get; set; } = new();

    /// <summary>
    /// Gets or sets the number of occurrences of this log (after deduplication).
    /// </summary>
    public int OccurrenceCount { get; set; } = 1;

    /// <summary>
    /// Gets or sets the AI-identified likely cause of the issue.
    /// </summary>
    public string? LikelyCause { get; set; }

    /// <summary>
    /// Gets or sets the AI-suggested fixes for the issue.
    /// </summary>
    public List<string>? SuggestedFixes { get; set; }

    /// <summary>
    /// Gets or sets reference links for more information.
    /// </summary>
    public List<string>? ReferenceLinks { get; set; }

    /// <summary>
    /// Gets or sets the severity assessment from AI.
    /// </summary>
    public string? SeverityAssessment { get; set; }
}